Consumer/urls.py
from django.contrib import admin
from django.urls import path
from Consumer.views import Consumerview

urlpatterns = [
    path("",  Consumerview.as_view()),


]

Evoucher/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('voucher/',include('Voucher.urls')),
    #path("Admin/",include("Admin.urls")),
    path("consumer/",include("Consumer.urls")),
    path("merchant/",include("Merchant.urls")),

]

Merchant/urls.py
from django.contrib import admin
from django.urls import path
from Merchant.views import Merchantview

urlpatterns = [
    path("",Merchantview.as_view() ),


]

Voucher/urls.py
from django.contrib import admin
from django.urls import path
from Voucher.views import Voucherview,Vouchershow,Voucherassign
from Voucher import views

app_name = 'Voucher'
urlpatterns = [
    path("see/", Voucherview.as_view() ),
    path("", views.index,),
    path("show/",Vouchershow.as_view(),name='show'),
    path("assign/", Voucherassign.as_view(),name='assign'),


]

Consumer/models.py
from django.db import models
#from Voucher.models import Voucher

class Consumer(models.Model):
     mobile = models.IntegerField()
     code = models.CharField(max_length=15)

Merchant/models.py
from django.db import models

# Create your models here.

Voucher/models.py
from django.db import models

class Voucher(models.Model):
    code = models.CharField(max_length=15,unique=True)
    face_value=models.IntegerField()
    start_date=models.DateField()
    expiry_date=models.DateField()

Consumer/forms.py
from django import  forms
from Consumer.models import Consumer

class ConsumerForm(forms.ModelForm):
    mobile = forms.IntegerField()
    code = forms.CharField(max_length=15)

    class Meta:
        model=Consumer
        fields=('mobile',
                'code',
                )

class ConsumervouchForm(forms.Form):
    mobile = forms.IntegerField()

Merchant/forms.py
from django import  forms


class MerchantForm(forms.Form):
    code = forms.CharField()

Voucher/forms.py
from django import  forms
from Voucher.models import Voucher

class VoucherForm(forms.ModelForm):
    code = forms.CharField(max_length=15)
    face_value = forms.IntegerField()
    start_date = forms.DateField()
    expiry_date = forms.DateField()
    class Meta:
        model=Voucher
        fields=('code',
                'face_value',
                'start_date',
                'expiry_date',)

Consumer/views.py
from django.shortcuts import render,redirect,HttpResponse
from .forms import ConsumervouchForm
from .models import Consumer
from Voucher.models import Voucher
from django.views.generic import TemplateView

class Consumerview(TemplateView):

    def get(self,request):
        form = ConsumervouchForm()
        return render(request, 'Consumer/vouchsearch.html', {'form': form})

    def post(self, request):

            form = ConsumervouchForm(request.POST)
            if form.is_valid():
                m=form.cleaned_data['mobile']
                #return HttpResponse(m)
                cod=Consumer.objects.filter(mobile=m)

                for i in cod:
                    vouch=Voucher.objects.filter(code=i.code)
                n=[]
                for i in vouch:
                    n.append({'code': i.code,
                              'face_value': i.face_value,
                              'Start_date': i.start_date,
                              'expriy_date': i.expiry_date}
                             )
                return HttpResponse(n)
            else:
                return render(request, 'Consumer/stata.html', {'form': form})

    #return render(request, 'Consumer/status.html', {'form': form})

Merchant/views.py
from django.shortcuts import render,HttpResponse
from .forms import MerchantForm
from Voucher.models import Voucher
from Consumer.models import Consumer
from django.views.generic import TemplateView

class Merchantview(TemplateView):

    def get(self,request):
        form = MerchantForm()
        return render(request, 'Merchant/Merchantredeem.html', {'form': form})

    def post(self, request):

            form = MerchantForm(request.POST)
            if form.is_valid():
                cod=form.cleaned_data['code']
                m=Consumer.objects.get(code=cod).mobile
                vouch=Voucher.objects.get(code=cod)
                n=[]
                n.append({'code': vouch.code,
                              'face_value': vouch.face_value,
                              'Start_date': vouch.start_date,
                              'expriy_date': vouch.expiry_date,
                              'mobile':m,
                          }
                             )
                return HttpResponse(n)
            else:
                return render(request, 'Merchant/stata.html', {'form': form})

Voucher/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from .forms import VoucherForm
from .models import Voucher
from django.views.generic import TemplateView
from django.shortcuts import render,HttpResponse,redirect
from Voucher.models import Voucher
from Consumer.forms import ConsumerForm


class Voucherview(TemplateView):
    template_name = 'voucher/voucher.html'

    def get(self,request):
        form = VoucherForm()
        return render(request, self.template_name, {'form': form})


    def post(self,request):
        form = VoucherForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("Voucher added")

        return render(request, self.template_name, {'form': form})


class Vouchershow(TemplateView):
    def post(self,request):
        voucher=Voucher.objects.all()
        n = []
        for i in voucher:
            n.append({'code': i.code,
                  'face_value': i.face_value,
                  'Start_date': i.start_date,
                  'expriy_date': i.expiry_date}
                 )

        return HttpResponse(n)




class Voucherassign(TemplateView):
    def get(self,request):
        form = ConsumerForm()
        return render(request, 'voucher/consumerform.html', {'form': form})

    def post(self,request):
        form = ConsumerForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            return render(request, 'voucher/stata.html', {'form': form})

        return render(request, 'voucher/status.html', {'form': form})




def index(request):
    return  render(request,'voucher/adminhome.html')

"""class get_data():
    template_name='voucher/voucher.html'

    def get(self,request):
        form=VoucherForm()
        return render(request,self.template_name, {'form': form})

    def post(self,request):
        form=VoucherForm(request.POST)
        if form.is_valid():
            form.save()
        else:
            form=VoucherForm()
            code = form.cleaned_data('code')
            face_value = form.cleaned_data('face_value')
            start_date = form.cleaned_data('start_date')
            expiry_date = form.cleaned_data('expiry_date')
            form= VoucherForm()
            return  redirect('voucher:voucher')

        #args={'form':form,'code':code,'face_value':face_value,'start_date':start_date,'expiry_date':expiry_date}
        return render(request,self.template_name,{'form':form})"""

Consumer/templates/Consumer/stata.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>Unvalid mobile number</h1><br><br><br><br>

</body>
</html>

Consumer/templates/Consumer/status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Unvalid mobile number</h1>
</body>
</html>

Consumer/templates/Consumer/vouchsearch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <form method="POST">
      <fieldset>
        <legend>Form</legend>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Show my Voucher</button>
      </fieldset>
    </form>
</div>
</body>
</html>

Merchant/templates/Merchant/Merchantredeem.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>



<div class="container">
    <form method="POST">
      <fieldset>
        <legend>Form</legend>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Redeem</button>
      </fieldset>
    </form>
</div>

</body>
</html>

Merchant/templates/Merchant/stata.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>Unvalid code</h1><br><br><br><br>

</body>
</html>

Voucher/templates/voucher/adminhome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<button
    onclick="window.location.href = 'http://127.0.0.1:8000/voucher/see/';">
        VOUCHER
    </button>

<br><br><br>




<h2>Click here to see vouchers</h2>
<form action="{% url 'Voucher:show' %}" method="POST">
{% csrf_token %}
  <input type="submit" class="btn" value="Click" name="mybtn">
</form><br><br><br>


<h2>Click here to assign vouchers</h2>
<form action="{% url 'Voucher:assign' %}" >
{% csrf_token %}
  <input type="submit" class="btn" value="Click" name="mybtn">
</form>




    </body>
</html>

Voucher/templates/voucher/consumerform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


<button
    onclick="window.location.href = 'http://127.0.0.1:8000/voucher/';">
        AdminHome
    </button>


<div class="container">
    <form method="POST">
      <fieldset>
        <legend>Form</legend>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add Voucher to consumer</button>
      </fieldset>
    </form>
</div>




</body>
</html>

Voucher/templates/voucher/stata.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Please enter Unique code</h1><br><br><br><br>
<h1>put date in mm/day/year format</h1>
</body>
</html>

Voucher/templates/voucher/status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> voucher Added</h1>
</body>
</html>

Voucher/templates/voucher/voucher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <form method="POST">
      <fieldset>
        <legend>Form</legend>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Add Voucher</button>
      </fieldset>
    </form>
</div>
</body>
</html>